#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: yes
private methods: yes

---
snippet: "
  {
    class A {
      static #a() { return 1; }
    }
  }
"
frame size: 8
parameter count: 1
bytecode array length: 67
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(CreateClosure), U8(4), U8(1), U8(2),
                B(StaCurrentContextSlot), U8(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaCurrentContextSlot), U8(5),
                B(Star), R(6),
                B(CallRuntime), U16(Runtime::kAddPrivateBrand), R(5), U8(2),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   84 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  {
    class A {
      static get #a() { return 1; }
    }
  }
"
frame size: 9
parameter count: 1
bytecode array length: 77
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(CreateClosure), U8(4), U8(1), U8(2),
                B(Star), R(7),
                B(LdaNull),
                B(Star), R(8),
                B(CallRuntime), U16(Runtime::kCreatePrivateAccessors), R(7), U8(2),
                B(StaCurrentContextSlot), U8(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaCurrentContextSlot), U8(5),
                B(Star), R(6),
                B(CallRuntime), U16(Runtime::kAddPrivateBrand), R(5), U8(2),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   88 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  {
    class A {
      static set #a(val) { }
    }
  }
"
frame size: 9
parameter count: 1
bytecode array length: 77
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(LdaNull),
                B(Star), R(7),
                B(CreateClosure), U8(4), U8(1), U8(2),
                B(Star), R(8),
                B(CallRuntime), U16(Runtime::kCreatePrivateAccessors), R(7), U8(2),
                B(StaCurrentContextSlot), U8(4),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaCurrentContextSlot), U8(5),
                B(Star), R(6),
                B(CallRuntime), U16(Runtime::kAddPrivateBrand), R(5), U8(2),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   81 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  {
    class A {
      static get #a() { return 1; }
      static set #a(val) { }
    }
  }
"
frame size: 9
parameter count: 1
bytecode array length: 95
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(5),
                B(CreateClosure), U8(4), U8(1), U8(2),
                B(Star), R(7),
                B(LdaNull),
                B(Star), R(8),
                B(CallRuntime), U16(Runtime::kCreatePrivateAccessors), R(7), U8(2),
                B(StaCurrentContextSlot), U8(4),
                B(CreateClosure), U8(5), U8(2), U8(2),
                B(Star), R(8),
                B(LdaCurrentContextSlot), U8(4),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kStorePrivateSetter), R(7), U8(2),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaCurrentContextSlot), U8(5),
                B(Star), R(6),
                B(CallRuntime), U16(Runtime::kAddPrivateBrand), R(5), U8(2),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*  115 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

---
snippet: "
  {
    class A {
      static #a() { }
      #b() { }
    }
  }
"
frame size: 8
parameter count: 1
bytecode array length: 87
bytecodes: [
  /*   30 E> */ B(StackCheck),
                B(CreateBlockContext), U8(0),
                B(PushContext), R(2),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(4),
                B(LdaTheHole),
                B(StaCurrentContextSlot), U8(5),
                B(LdaTheHole),
                B(Star), R(6),
                B(CreateClosure), U8(2), U8(0), U8(2),
                B(Star), R(3),
                B(LdaConstant), U8(1),
                B(Star), R(4),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(6),
                B(LdaConstant), U8(3),
                B(Star), R(7),
                B(CallRuntime), U16(Runtime::kCreatePrivateNameSymbol), R(7), U8(1),
                B(StaCurrentContextSlot), U8(7),
                B(CreateClosure), U8(4), U8(1), U8(2),
                B(StaCurrentContextSlot), U8(4),
                B(CreateClosure), U8(5), U8(2), U8(2),
                B(StaCurrentContextSlot), U8(5),
                B(Mov), R(3), R(5),
                B(CallRuntime), U16(Runtime::kDefineClass), R(4), U8(3),
                B(Star), R(4),
                B(Mov), R(5), R(1),
                B(LdaCurrentContextSlot), U8(7),
                B(Star), R(6),
                B(CallRuntime), U16(Runtime::kAddPrivateBrand), R(5), U8(2),
                B(PopContext), R(2),
                B(Mov), R(1), R(0),
                B(LdaUndefined),
  /*   87 S> */ B(Return),
]
constant pool: [
  SCOPE_INFO_TYPE,
  FIXED_ARRAY_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["A"],
  SHARED_FUNCTION_INFO_TYPE,
  SHARED_FUNCTION_INFO_TYPE,
]
handlers: [
]

